// ACTION TYPES

export const actionTypes = {
    GET_TEAMS_SUCCESS:"GET_TEAMS_SUCCESS",
    LOAD_TEAMS:"LOAD_TEAMS",
    GET_PLAYERS_SUCCESS:"GE_PLAYERS_SUCCESS",
    LOAD_PLAYERS:"LOAD_PLAYERS",
    SELECT_TEAMS:"SELECT_TEAMS",
    SELECT_PLAYERS:"SELECT_PLAYERS",
    RECORD_GAME:"RECORD_GAME"
}

// VIEW STATES

// export const DEFAULT_VIEW_STATE = "DEFAULT_VIEW_STATE";  ... DON'T THINK I NEED THIS

export const viewStates = {
    QUICK_RECORD_VIEW:"QUICK_RECORD_VIEW",
    SELECT_PLAYERS_VIEW:"SELECT_PLAYERS_VIEW",
    SETUP_GAME_VIEW:"setup_game_view",
    SELECT_GAME_VIEW:"SELECT_GAME_VIEW",
    RECORD_GAME_VIEW:"RECORD_GAME_VIEW",
    DEFAULT_GAME_VIEW:"DEFAULT_GAME_VIEW"
}






