// ACTION TYPES

export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const LOAD_TEAMS = 'LOAD_TEAMS';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS'
export const LOAD_PLAYERS = 'LOAD_PLAYERS'
export const SELECT_TEAMS = 'SELECT_TEAMS'
export const SELECT_PLAYER = 'SELECT_PLAYER'
export const RECORD_GAME = 'RECORD_GAME'


// VIEW STATES


export const DEFAULT_VIEW_STATE = 'DEFAULT_VIEW_STATE';
export const QUICK_RECORD_VIEW = "QUICK_RECORD_VIEW";
export const SELECT_PLAYERS_VIEW = "SELECT_PLAYERS_VIEW";
export const SELECT_LOCATION_TEAMS_VIEW = "SELECT_LOCATION_TEAMS_VIEW";
export const SELECT_GAME_VIEW = "SELECT_GAME_VIEW";
export const RECORD_GAME_VIEW = "RECORD_GAME_VIEW";
export const VIEW_GAME = "VIEW_GAME";
